TimeTrack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from apps.core.views import frontpage, privacy, terms, plans, signup


urlpatterns = [
    path("", frontpage, name="frontpage"),
    path("privacy/", privacy, name="privacy"),
    path("terms/", terms, name="terms"),
    path('plans/', plans, name="plans"),
    path('admin/', admin.site.urls),

    # Dashboard
    path('dashboard/', include('apps.dashboard.urls')),

    # Auth
    path('signup/', signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html"),  name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

apps/team/urls.py
# import Django

# because our apps can have many add so we will create namespace

from django.urls import path

from .api import create_checkout_session, stripe_webhook
from .views import add, team, edit, activate_team, invite, plans, plans_thankyou

app_name = 'team'

urlpatterns = [
    path('add/', add, name="add"),
    path('<int:team_id>/', team, name="team"),
    path('invite/', invite, name="invite"),
    path('edit/', edit, name="edit"),
    path('plans/', plans, name="plans"),
    path('plans/thank_you/', plans_thankyou, name="plans_thankyou"),
    path('activate_team/<int:team_id>/', activate_team, name="activate_team"),

    # API
    path('api/stripe_webhook/', stripe_webhook, name='stripe_webhook'),
    path('api/create_checkout_session/', create_checkout_session,
         name='create_checkout_session'),
]

apps/userprofile/urls.py
from django.urls import path
from .views import myaccount, edit_profile, accept_invitation


urlpatterns = [
    path('', myaccount, name="myaccount"),
    path('edit_profile/', edit_profile, name="edit_profile"),
    path('accept_invitation/', accept_invitation, name='accept_invitation')
]

apps/team/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Plan(models.Model):
    title = models.CharField(max_length=255)
    max_projects_per_team = models.IntegerField(default=0)
    max_members_per_team = models.IntegerField(default=0)
    max_tasks_per_project = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    # plan status
    PLAN_ACTIVE = 'active'
    PLAN_CANCELLED = 'cancelled'

    CHOICES_PLAN_STATUS = (
        (PLAN_ACTIVE, 'Active'),
        (PLAN_CANCELLED, 'Cancelled')
    )

    # Fields
    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(
        User, related_name="created_teams", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    plan = models.ForeignKey(Plan, related_name='teams',
                             on_delete=models.CASCADE)
    plan_end_date = models.DateTimeField(blank=True, null=True)
    plan_status = models.CharField(
        max_length=20, choices=CHOICES_PLAN_STATUS, default=PLAN_ACTIVE)
    stripe_customer_id = models.CharField(
        max_length=255, blank=True, null=True)
    stripe_subscription_id = models.CharField(
        max_length=255, blank=True, null=True)

   # sorted by title
    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Invitation(models.Model):
    INVITED = 'Invited'
    ACCEPTED = 'accepted'

   # choices is iterable containing actual values and human readable values
    CHOICES_STATUS = (
        (INVITED, 'invited'),
        (ACCEPTED, 'Accepted')
    )
    team = models.ForeignKey(
        Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(
        max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Userprofile(models.Model):
    user = models.OneToOneField(
        User, related_name='userprofile', on_delete=models.CASCADE)
    active_team_id = models.IntegerField(default=0)
    avatar = models.ImageField(
        upload_to='uploads/avatars/', blank=True, null=True)

    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return '/static/images/avatar.png'

apps/userprofile/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.

# import User model
from .models import Userprofile
from apps.team.models import Team, Invitation
from apps.team.utilities import send_invitation_accepted


@login_required
def myaccount(request):
    teams = request.user.teams.exclude(
        pk=request.user.userprofile.active_team_id)
    invitations = Invitation.objects.filter(
        email=request.user.email, status=Invitation.INVITED)
    return render(request, 'userprofile/myaccount.html', {'teams': teams, 'invitations': invitations})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        request.user.first_name = request.POST.get('first_name', '')
        request.user.last_name = request.POST.get('last_name', '')
        request.user.email = request.POST.get('email', '')
        request.user.save()

        if request.FILES:
            avatar = request.FILES['avatar']
            userprofile = request.user.userprofile
            userprofile.avatar = avatar
            userprofile.save()

        messages.info(request, 'Your changes are saved')

        return redirect('myaccount')

    return render(request, 'userprofile/edit_profile.html')


@login_required
def accept_invitation(request):
    if request.method == 'POST':

        # check if code is correct
        code = request.POST.get('code')

        invitations = Invitation.objects.filter(
            code=code, email=request.user.email)

        if invitations:
            invitation = invitations[0]
            invitation.status = Invitation.ACCEPTED
            invitation.save()

            # add this user as member to the team
            team = invitation.team
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            messages.info(request, 'Invitation accepted')

            send_invitation_accepted(team, invitation)
            return redirect('team:team', team_id=team.id)
        else:
            messages.info(request, "Invitation was not found")

    else:
        return render(request, 'userprofile/accept_invitation.html')

apps/userprofile/templates/userprofile/accept_invitation.html
{% extends 'core/base.html' %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block title %} Accept invitation | {% endblock %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block content %} {% comment %}
<!--------------------------------->
{% endcomment %}
{% load static %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    <li><a href="{% url 'myaccount' %}">My account</a></li>
    <li class="is-active">
      <a href="{% url 'accept_invitation' %}" aria-current="page"
        >Accept invitation</a
      >
    </li>
  </ul>
</nav>

<div class="columns">
  <div class="column is-4">
    <h1 class="title">Accept invitation</h1>
     <form method="post" action=".">
         {% csrf_token %}

         <div class="field">
           <label>Code ( from e-mail )</label>

           <div class="control">
             <input type="text" name="code" id="id_code" class="input">
           </div>
         </div>

         <div class="field">
           <div class="control">
             <button class="button is-info">Accept</button> 
           </div>
         </div>
      </form>

  </div>
</div>
{% endblock %}

apps/userprofile/templates/userprofile/edit_profile.html
{% extends 'core/base.html' %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block title %} Edit Profile | {% endblock %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block content %} {% comment %}
<!--------------------------------->
{% endcomment %}
{% load static %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    <li><a href="{% url 'myaccount' %}">My account</a></li>
    <li class="is-active">
      <a href="{% url 'edit_profile' %}" aria-current="page"
        >Edit Profile</a
      >
    </li>
  </ul>
</nav>

<div class="columns">
  <div class="column is-4">
    <h1 class="title">Edit Profile</h1>

    <form method="post" action="." enctype="multipart/form-data">
      {% csrf_token %}

      <div class="field">
      <label>First name</label>
        <input
          type="text"
          name="first_name"
          id="first_name"
          class="input"
          {% if request.user.first_name %}
          value="{{ request.user.first_name }}"
          {% endif %}
        />
      </div>
      <div class="field">
         <label>Last name</label>
        <input
          type="text"
          name="last_name"
          id="last_name"
          class="input"
          {% if request.user.last_name %}
          value="{{ request.user.last_name }}"
          {% endif %}
        />
      </div>

      <div class="field">
        <label>Email</label>
        <input
          type="email"
          name="email"
          id="email"
          class="input"
          {% if request.user.email %}
          value="{{ request.user.email }}"
          {% endif %}
        />
      </div>

      <div class="field">
        <label>Avatar</label>
        <figure class="image is-64x64 avatar-editimage">
           <img class="is-rounded" src="{{ request.user.userprofile.get_avatar }}"/>
        </figure>
        <div class="control mt-2">
          {% comment %} <input type="file" name="avatar" id="id_avatar" class="input"> {% endcomment %}
          <div class="file has-name">
            <label class="file-label">
              <input class="file-input" type="file" id="id_avatar" name="avatar">
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                  Choose a file…
                </span>
              </span>
              <span class="file-name">
                {{ request.user.userprofile.get_avatar }}
              </span>
            </label>
         </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <button class="button is-info">Save changes</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

apps/userprofile/templates/userprofile/login.html
{% extends 'core/base.html' %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block title %} Log in | {% endblock %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block content %} {% comment %}
<!--------------------------------->
{% endcomment %}
<section class="hero" id="hero--body">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Log in</h1>
      <h2 class="subtitle hero--body--title">
        Log in to your account and <span class="blue">start</span> tracking time
      </h2>
    </div>
  </div>
</section>

<div class="columns" id="signup-app">
  <div class="column is-6 is-offset-3">
    <form method="post" action="." class="mt-6" v-on:submit="validateForm">
      {% csrf_token %}
      <!-------------------------->
      {% if form.errors %}
      <div class="notification is-danger">
        {{ form.non_field_errors }}
        <!-------------------------->
        {% for field in form %}
        <!-------------------------->
        {% if field.errors %}
        <!-------------------------->
        {{ field.label }}: {{ field.errors|striptags }} {% endif %}
        <!-------------------------->
        {% endfor%}
      </div>
      {% endif %}

      <div class="field">
        <label>Email</label>
        <div class="control">
          <input type="email" name="username" id="id_username" class="input" />
        </div>
      </div>

      <div class="field">
        <label>Password</label>
        <div class="control">
          <input
            type="password"
            name="password"
            id="id_password"
            class="input"
          />
        </div>
      </div>

      <div class="field">
        <div class="control">
          <button class="button is-success">Log in</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

apps/userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %} {% comment %}
<!------------------------------->{% endcomment %} {% block title %} Sign up |
{% endblock %} {% load static %}{% comment %}

<!--------------------------------->
{% endcomment %} {% block content %} {% load static %}

<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    <li>
      <a class="is-active" href="{% url 'myaccount' %}" aria-current="page"
        >My account</a
      >
    </li>
  </ul>
</nav>

<div class="columns">
  <div class="column is-8">
    <div class="media mb-4">
      <div class="media-left">
        <figure class="image is-64x64">
           <img src="{{user.userprofile.get_avatar}}">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-3">{% firstof user.get_full_name user.username %}</p>
        <p class="subtitle is-6">{{ user.email }}</p>
      </div>
    </div>
    <div class="pt-4">
      <a href="{% url 'edit_profile' %}" class="button is-info"> <i class="fas fa-marker"></i>Edit profile</a>
      <a href="{% url 'logout' %}" class="button is-danger is-outlined">Log out</a>
    </div>
  </div>
  <div class="picture colum is-4">
    <img class="account-img" src="{% static 'images/icon.png' %}" />
  </div>
</div>

<hr>
{% if invitations %}
<div class="team team-invitation">
  <h2><i class="fas fa-user-friends icon-new"></i>You have pending invitations</h2>

<ol type="1">
  {% for invitation in invitations %}
    <li><a href="{% url 'accept_invitation' %}"><span class="invite-team-link">{{ invitation.team.title }}</span></a></li>
  {% endfor %}
</ol>
</div>
{% endif %}

<div class="columns">
   <div class="column is-12">
      <h2 class="subtitle team-title">Teams</h2>

      <a href="{% url 'team:add' %}" class="button add-team is-medium is-fullwidth">
      <i class="fas fa-plus"></i>
      Add Team</a>
   </div>
</div>

<div class="columns ">
    {% if active_team %}
       <div class="column is-4 ">
      <div class="notification has-background-success-light team">
         <h3 class="is-size-5">
         {{ active_team.title }}
         {% if active_team.created_by == request.user %} (Owner)
         {% else %} (Member)
         {% endif %}
          </h3>
          <h3 class="is-size-6">SHOW PLAN HERE</h3>

          <hr>

          <a href="{% url 'team:team' active_team.id %}" class="button is-info is-light">
           <i class="fas fa-info-circle"></i>
            Details
          </a>
          {% if active_team.created_by == request.user %}
          <a href="#" class="button is-info">
              <i class="fas fa-retweet"></i>
              INVITE USERS
          </a>
          {% endif %}
        

      </div>
   </div>
    {% endif %}
   {% for team in teams %}
   <div class="column is-4">
      <div class="notification not-activated-team">
         <h3 class="is-size-5">
         {{ team.title }}
          </h3>
          <h3 class="is-size-6">SHOW PLAN HERE</h3>

          <hr>
          <a href="{% url 'team:team' team.id %}" class="button is-info is-light">
           <i class="fas fa-info-circle"></i>
            Details
          </a>
          <a href="{% url 'team:activate_team' team.id %}" class="button is-info">
             <i class="fas fa-hand-sparkles"></i>
             Activate
          </a>

      </div>
   </div>
   {% endfor %}
</div>

{% endblock %}

apps/userprofile/templates/userprofile/signup.html
{% extends 'core/base.html' %}
<!--------------------------------->
{% block title %} Sign up | {% endblock %}
<!--------------------------------->
{% block content %}
<!--------------------------------->
<section class="hero" id="hero--body">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Sign up</h1>
      <h2 class="subtitle hero--body--title">
        Get a <span class="blue">free</span> account and start tracking time
      </h2>
    </div>
  </div>
</section>

<div class="columns" id="signup-app">
  <div class="column is-6 is-offset-3">
    <form
      method="post"
      action="."
      class="mt-6"
      v-on:submit="validateForm"
      novalidate
    >
      {% csrf_token %}
      <!-------------------------->
      {% if form.errors %}
      <div class="notification is-danger">
        {{ form.non_field_errors }}
        <!-------------------------->
        {% for field in form %}
        <!-------------------------->
        {% if field.errors %}
        <!-------------------------->
        {{ field.label }}: {{ field.errors|striptags }} {% endif %}
        <!-------------------------->
        {% endfor%}
      </div>
      {% endif %}

      <div class="notification is-danger" v-if="errors.length">
        <p v-for="error in errors">[[error]]</p>
      </div>
      <div class="field">
        <label>Email</label>
        <div class="control">
          <input
            type="email"
            name="username"
            id="id_username"
            class="input"
            v-model="username"
          />
        </div>
      </div>

      <div class="field">
        <label>Password</label>
        <div class="control">
          <input
            type="password"
            name="password1"
            id="id_password1"
            class="input"
            v-model="password1"
          />
        </div>
      </div>

      <div class="field">
        <label>Repeat Password</label>
        <div class="control">
          <input
            type="password"
            name="password2"
            id="id_password2"
            class="input"
            v-model="password2"
          />
        </div>
      </div>

      <ul class="password-helt-text">
        <li v-if="password1.length < 8">
          Your password must contain at least 8 characters
        </li>
        <li v-if="!isNaN(password1)">You password can't be entirely numeric</li>
      </ul>

      <div class="field">
        <div class="control">
          <button class="button is-success">Sign up</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %} {% block scripts %}
<script>
  const SignupApp = {
    data() {
      return {
        username: "",
        password1: "",
        password2: "",
        errors: [],
      };
    },
    delimiters: ["[[", "]]"],
    methods: {
      validateForm(e) {
        this.errors = [];

        if (!this.validateEmail(this.username)) {
          this.errors.push("Your email address is not valid");
        }

        if (this.password1 === "") {
          this.errors.push("Your password is missing");
        }

        if (this.password1.length < 8) {
          this.errors.push("Password must be at least 8 characters");
        }

        // contains all numbers
        if (!isNaN(this.password1)) {
          this.errors.push("You password can't be entirely numeric");
        }

        if (this.password1 !== this.password2) {
          this.errors.push("You passwords do not match!");
        }

        if (this.errors.length) {
          e.preventDefault();
          return false;
        } else {
          return true;
        }
      },
      validateEmail(email) {
        if (
          /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(
            email
          )
        ) {
          return true;
        }
        return false;
      },
    },
  };
  Vue.createApp(SignupApp).mount("#signup-app");
</script>
{% endblock %}