TimeTrack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from apps.core.views import frontpage, privacy, terms, plans, signup


urlpatterns = [
    path("", frontpage, name="frontpage"),
    path("privacy/", privacy, name="privacy"),
    path("terms/", terms, name="terms"),
    path('plans/', plans, name="plans"),
    path('admin/', admin.site.urls),

    # Dashboard
    path('dashboard/', include('apps.dashboard.urls')),

    # Auth
    path('signup/', signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html"),  name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

apps/team/urls.py
# import Django

# because our apps can have many add so we will create namespace

from django.urls import path

from .api import create_checkout_session, stripe_webhook
from .views import add, team, edit, activate_team, invite, plans, plans_thankyou

app_name = 'team'

urlpatterns = [
    path('add/', add, name="add"),
    path('<int:team_id>/', team, name="team"),
    path('invite/', invite, name="invite"),
    path('edit/', edit, name="edit"),
    path('plans/', plans, name="plans"),
    path('plans/thank_you/', plans_thankyou, name="plans_thankyou"),
    path('activate_team/<int:team_id>/', activate_team, name="activate_team"),

    # API
    path('api/stripe_webhook/', stripe_webhook, name='stripe_webhook'),
    path('api/create_checkout_session/', create_checkout_session,
         name='create_checkout_session'),
]

apps/team/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Plan(models.Model):
    title = models.CharField(max_length=255)
    max_projects_per_team = models.IntegerField(default=0)
    max_members_per_team = models.IntegerField(default=0)
    max_tasks_per_project = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    # plan status
    PLAN_ACTIVE = 'active'
    PLAN_CANCELLED = 'cancelled'

    CHOICES_PLAN_STATUS = (
        (PLAN_ACTIVE, 'Active'),
        (PLAN_CANCELLED, 'Cancelled')
    )

    # Fields
    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(
        User, related_name="created_teams", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    plan = models.ForeignKey(Plan, related_name='teams',
                             on_delete=models.CASCADE)
    plan_end_date = models.DateTimeField(blank=True, null=True)
    plan_status = models.CharField(
        max_length=20, choices=CHOICES_PLAN_STATUS, default=PLAN_ACTIVE)
    stripe_customer_id = models.CharField(
        max_length=255, blank=True, null=True)
    stripe_subscription_id = models.CharField(
        max_length=255, blank=True, null=True)

   # sorted by title
    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Invitation(models.Model):
    INVITED = 'Invited'
    ACCEPTED = 'accepted'

   # choices is iterable containing actual values and human readable values
    CHOICES_STATUS = (
        (INVITED, 'invited'),
        (ACCEPTED, 'Accepted')
    )
    team = models.ForeignKey(
        Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(
        max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/team/views.py
# import python
from apps.team.utilities import send_invitation
import random
import stripe

from datetime import datetime

# import django
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

# Create your views here.
from .models import Team, Invitation, Plan

# import helpers
from .utilities import send_invitation

# Views


# members_in means checking logged user is a member of team
@login_required
def team(request, team_id):
    team = get_object_or_404(
        Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    invitations = team.invitations.filter(status=Invitation.INVITED)
    return render(request, 'team/team.html', {'team': team, 'invitations': invitations})


@login_required
def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()

           # in userProfile model I have active_team_id
            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            return redirect('myaccount')

    return render(request, 'team/add.html')


@login_required
def edit(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id,
                             status=Team.ACTIVE, members__in=[request.user])

    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            team.title = title
            team.save()

            messages.info(request, 'The changes were saved')

            return redirect('team:team', team_id=team.id)

    return render(request, 'team/edit.html', {'team': team})


@login_required
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id,
                             status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team.id
    userprofile.save()

    messages.info(request, 'The new team is activated ')
    return redirect('team:team', team_id=team.id)


@login_required
def invite(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id,
                             status=Team.ACTIVE)
    if request.method == 'POST':
        email = request.POST.get('email')

        # check this email hasnot been invited before
        if email:
            invitations = Invitation.objects.filter(team=team, email=email)

            if not invitations:
                # create four letter string
                code = ''.join(random.choice(
                    'abcdefghijklmnopqrstuvwxyz0123456789') for i in range(4))
                invitation = Invitation.objects.create(
                    team=team, email=email, code=code)

                messages.info(request, 'The user was invited')

                # user helper func to send invitation
                send_invitation(email, code, team)

                return redirect('team:team', team_id=team.id)
            else:
                messages.info(request, 'The user has already been invited')

    return render(request, 'team/invite.html', {'team': team})


@login_required
def plans(request):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    error = ''

    if request.GET.get('cancel_plan', ''):
        try:
            plan_default = Plan.objects.get(is_default=True)

            team.plan = plan_default
            team.plan_status = Team.PLAN_CANCELLED
            team.save()

            # cancel subscription
            stripe.api_key = settings.STRIPE_SECRET_KEY
            stripe.Subscription.delete(team.stripe_subscription_id)
        except Exception:
            error = 'Something went wrong with the cancellation. Please try again!'

    context = {
        'team': team,
        'error': error,
        'stripe_pub_key': settings.STRIPE_PUBLISHABLE_KEY
    }

    return render(request, 'team/plans.html', context)


@login_required
def plans_thankyou(request):
    error = ''

    try:
        team = get_object_or_404(
            Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
        stripe.api_key = settings.STRIPE_SECRET_KEY

        # subscription and product from stripe
        subscription = stripe.Subscription.retrieve(
            team.stripe_subscription_id)
        product = stripe.Product.retrieve(subscription.plan.product)

        team.plan_status = Team.PLAN_ACTIVE
        team.plan_end_date = datetime.fromtimestamp(
            subscription.current_period_end)

        # team plan to whatever comes from stripe(this name is of product in stripe we created)
        team.plan = Plan.objects.get(title=product.name)
        team.save()
    except Exception:
        error = 'There something wrong. Please try again!'

    return render(request, 'team/plans_thankyou.html', {'error': error})

apps/team/templates/team/add.html
{% extends 'core/base.html' %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block title %} Add Team | {% endblock %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block content %} {% comment %}
<!--------------------------------->
{% endcomment %}
{% load static %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    <li><a href="{% url 'team:add' %}">Add team</a></li>
    <li>
      <a class="is-active" href="{% url 'edit_profile' %}" aria-current="page"
        >Edit Profile</a
      >
    </li>
  </ul>
</nav>

<div class="columns" id="team-app">
  <div class="column is-4">
    <h1 class="title">Add team</h1>

    <form method="post" action="." @submit="validateForm">
      {% csrf_token %}

      <div class="field">
         <label>Title</label>
         <div class="control">
            <input class="input is-info" type="text" name="title" id="id_title" v-model="title">
         </div>
      </div>

      <div class="notification is-danger" v-if="errors.length">
        <p v-for="error in errors">[[ error ]]></p>
      </div>

      <div class="field">
        <div class="control">
          <button class="button is-info">Submit</button>
        </div>
      </div>

    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  const TeamApp = {
      data() {
          return {
              title: '',
              errors: []
          }
      },
      delimiters: ['[[',']]'],
      methods: {
          validateForm(e) {
             this.errors = [] 

             if(this.title){
                 return true
             }

             e.preventDefault()

             this.errors.push('The title field is missing')
             return false
          }
      }
  }

  Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/edit.html
{% extends 'core/base.html' %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block title %} Edit Team | {% endblock %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block content %} {% comment %}
<!--------------------------------->
{% endcomment %}
{% load static %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    <li><a href="{% url 'team:edit' %}">Edit team</a></li>
    <li class="is-active">
      <a href="{% url 'edit_profile' %}" aria-current="page"
        >Edit Profile</a
      >
    </li>
  </ul>
</nav>

<div class="columns" id="team-app">
  <div class="column is-4">
    <h1 class="title">Edit team</h1>

    <form method="post" action="." @submit="validateForm">
      {% csrf_token %}

      <div class="field">
         <label>Title</label>
         <div class="control">
            <input class="input is-info" type="text" name="title" id="id_title" v-model="title">
         </div>
      </div>

      <div class="notification is-danger" v-if="errors.length">
        <p v-for="error in errors">[[ error ]]></p>
      </div>

      <div class="field">
        <div class="control">
          <button class="button is-info">Save changes</button>
        </div>
      </div>

    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  const TeamApp = {
      data() {
          return {
              title: '{{ team.title }}',
              errors: []
          }
      },
      delimiters: ['[[',']]'],
      methods: {
          validateForm(e) {
             this.errors = [] 

             if(this.title){
                 return true
             }

             e.preventDefault()

             this.errors.push('The title field is missing')
             return false
          }
      }
  }

  Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/email_accepted_invitation.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Minutos</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <style type="text/css">
      html {
        width: 100%;
      }

      body {
        width: 100%;
        font-family: Arial;
        font-size: 1rem;
        background-color: #fff;
        color: #333;
      }

      a {
        color: #111;
      }
    </style>
  </head>
  <body>
    <table width="100%" cellspacing="0" cellpadding="0">
      <tr>
        <td><h1>Minutos</h1></td>
      </tr>

      <tr>
        <td>
          <p>{{ invitation.email }} accepted your invitation.</p>
        </td>
      </tr>
    </table>

    <script src="" async defer></script>
  </body>
</html>

apps/team/templates/team/email_invitation.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Minutos</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <style type="text/css">
      html {
        width: 100%;
      }

      body {
        width: 100%;
        font-family: Arial;
        font-size: 1rem;
        background-color: #fff;
        color: #333;
      }

      a {
        color: #111;
      }
    </style>
  </head>
  <body>
    <table width="100%" cellspacing="0" cellpadding="0">
      <tr>
        <td><h1>Minutos - Invitation to {{ team.title }}</h1></td>
      </tr>

      <tr>
        <td>
          <p>You have been invited to join {{team.title}}</p>
          <p>
            Click the link to sign up or log in. Your team activation code is {{ code }}
          </p>
        </td>
      </tr>

      <tr>
        <td>
          <a href="{{ acceptation_url }}">Accept invitation</a>
        </td>
      </tr>
    </table>

    <script src="" async defer></script>
  </body>
</html>

apps/team/templates/team/invite.html
{% extends 'core/base.html' %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block title %} Invite member | {% endblock %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block content %} {% comment %}
<!--------------------------------->
{% endcomment %}
{% load static %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    {% comment %} team.id is primary key sending to  teams page to show details {% endcomment %}
    <li><a href="{% url 'team:team' team.id %}">{{ team.title }}</a></li>
     <li class="is-active">
      <a  href="{% url 'team:invite' %}" aria-current="page"
        >Invite member</a>
    </li>
  </ul>
</nav>

<div class="columns is-multiline" id="invite-app">
      <div class="column is-4">
          <h1 class="title">Invite member</h1>

          <div class="notification is-danger" v-if="errors.length">
              <p v-for="error in errors">[[ error ]]</p>
          </div>

          {% if team.plan.max_members_per_team > team.members.count %}
              <form method="post" action="." @submit="validateForm" novalite>
                  {% csrf_token %}

                  <div class="field">
                      <label>E-mail</label>

                      <div class="control">
                          <input type="email" name="email" id="id_email" v-model="email" class="input">
                      </div>
                  </div>

                  <div class="field">
                      <div class="control">
                          <button class="button is-success">Send invitation</button>
                      </div>
                  </div>
              </form>
          {% else %}
              <div class="notification is-warning">
                  This team has reached the limit of members.<br>

                  {% if team.created_by == request.user %}
                      <a href="{% url 'team:plans' %}">Upgrade plan</a>
                  {% else %}
                      Contact your team owner...
                  {% endif %}
              </div>
          {% endif %}
    </div>
</div>


{% endblock %}

{% block scripts %}
<script>
const InviteApp = {
    data() {
        return {
            email: '',
            errors: []
        }
    },
    delimiters: ["[[", "]]"],
    methods: {
        
        validateForm(e){
              if(this.validateEmail(this.email)){
                  return true
              }
              this.errors = ['The email is not valid']
              e.preventDefault()

              return false
        },
        validateEmail(email) {
            if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(
                email
            )
            ) {
            return true;
            }
            return false;
        }
    
   
    }
}
Vue.createApp(InviteApp).mount('#invite-app')
</script>
{% endblock %}

apps/team/templates/team/plans.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Plans| {% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    {% comment %} team.id is primary key sending to  teams page to show details {% endcomment %}
    <li><a href="{% url 'team:team' team.id %}">{{ team.title }}</a></li>
     <li class="is-active">
      <a href="{% url 'team:plans' %}" aria-current="page"
        >Plans</a>
    </li>
  </ul>
</nav>

<div class="columns mt-6" id="plans-app">
  <div class="column is-3">
    <div class="card card--plan">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4 media-content-text">Free</p>
            <p class="subtitle is-6 media-content-text">$0</p>
          </div>
        </div>

        <div class="content">
          <ul>
            <li>3 projects</li>
            <li>1 member</li>
            <li>10 tasks per project</li>
          </ul>

      
        </div>
      </div>
    </div>
  </div>

  <div class="column is-3">
    <div class="card card--plan">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4 media-content-text">Basic</p>
            <p class="subtitle is-6 media-content-text">$5</p>
          </div>
        </div>

        <div class="content">
          <ul>
            <li>10 projects</li>
            <li>15 members</li>
            <li>30 tasks per project</li>
          </ul>

          <hr />
          {% if team.plan.title == 'Basic' %}
            <a href="?cancel_plan=true" class="button is-danger">Cancel</a>
          {% else %}
            <a @click="subscribe('basic')" class="button is-primary">Start</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <div class="column is-3">
    <div class="card card--plan card--main">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4 media-content-text">Pro</p>
            <p class="subtitle is-6 media-content-text">$10</p>
          </div>
        </div>

        <div class="content">
          <ul>
            <li>25 projects</li>
            <li>50 members</li>
            <li>100 tasks per project</li>
          </ul>

          <hr />

          {% if team.plan.title == 'Pro' %}
            <a href="?cancel_plan=true" class="button is-danger">Cancel</a>
          {% else %}
            <a @click="subscribe('pro')" class="button is-primary">Start</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <div class="column is-3">
    <div class="card card--plan">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4 media-content-text">Need more?</p>
            <p class="subtitle is-6 media-content-text">$?</p>
          </div>
        </div>

        <div class="content">
          <ul>
            <li>Need more projects?</li>
            <li>Need more members?</li>
            <li>Need more tasks?</li>
          </ul>

          <hr />

          <a href="#" class="button is-primary">Contact us</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        const PlansApp = {
            data() {
                return {
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                subscribe(plan) {
                    console.log('Subscribe:', plan);

                    const stripe = Stripe('{{ stripe_pub_key }}');

                    fetch('/dashboard/myaccount/teams/api/create_checkout_session/', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify({
                            'plan': plan
                        })
                    })
                    .then(function(response) {
                        return response.json()
                    })
                    .then(function(session) {
                        console.log(session)
                        return stripe.redirectToCheckout({ sessionId: session.sessionId })
                    })
                    .then(function(result) {
                        if (result.error) {
                            console.log('Error:', result.error.message)
                        }
                    })
                    .catch(function(error) {
                        console.error('Error:', error);
                    });
                }
            }
        }

        Vue.createApp(PlansApp).mount('#plans-app')
    </script>
{% endblock %}

apps/team/templates/team/plans_thankyou.html
{% extends 'core/base.html' %}

{% block title %}Thank you | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li><a href="{% url 'team:plans' %}">Plans</a></li>
            <li class="is-active"><a href="{% url 'team:plans_thankyou' %}" aria-current="page">Thank you</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline">
        <div class="column is-12">
            {% if error %}
                <h1 class="title">Woops, something went wrong</h1>

                Go back to <a href="{% url 'team:plans' %}">plans</a> and try again or <a href="#">contact us</a>!
            {% else %}
                <h1 class="title">Thank you for purchasing a plan</h1>

                <a href="{% url 'dashboard' %}">Go to dashboard</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/team/templates/team/team.html
{% extends 'core/base.html' %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block title %} {{ team.title }} | {% endblock %} {% comment %}
<!--------------------------------->
{% endcomment %} {% block content %} {% comment %}
<!--------------------------------->
{% endcomment %}
{% load static %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">Dashboard</a></li>
    {% comment %} team.id is primary key sending to  teams page to show details {% endcomment %}
    <li class="is-active"><a href="{% url 'team:team' team.id %}">{{ team.title }}</a></li>
  </ul>
</nav>

<div class="columns is-multiline" id="team-app">
  <div class="column is-8">
    <h1 class="title">{{ team.title }}</h1>

    <div class="mb-3">
     <p><strong>Current plan: </strong>{{ team.plan.title }}</p>
      {% if team.plan.title != 'Free' %}
                <p><strong>Plan end date: </strong>{{ team.plan_end_date|date:"Y-m-d" }}{% if team.plan_status == 'active' %} (auto renewing){% endif %}</p>
      {% endif %}
    </div>

    {% if request.user == team.created_by %}
      <a href="{% url 'team:invite' %}" class="button is-primary"><i class="icon-new fas fa-retweet"></i>Invite users</a>
      <a href="{% url 'team:plans' %}" class="button is-primary is-outlined"><i class="icon-new fas fa-exchange-alt"></i>Change Plan</a>
    {% endif %}

    <hr>

    <h2 class="subtitle mt-6"> <i class="fas fa-user-friends icon-new"></i>Members</h2>
 <ol type="1">
    {% for member in team.members.all %}
        <li>{{ member.username }}</li>
    {% endfor %}
    </ol>
   <hr>
    <h2 class="subtitle mt-6"><i class="fas fa-people-arrows icon-new"></i>Invited Members</h2>

    <ol type="1">
      {% for member in invitations %}
        <li><span class="member-email">{{ member.email }}</span>- {{ member.date_sent|timesince }} ago</li>
      {% endfor %}
    </ol>

  </div>
  <div class="column is-4">
     <img src="{% static 'images/9814.jpg' %}"/>
  </div>
</div>


{%if team.created_by == request.user %}
 <div class="column is-4">
    <hr>

    <h3 class="subtitle">Owner actions</h3>
    <a href="{% url 'team:edit' %}" class="button is-warning"><i class="far fa-edit"></i>Edit team</a> 
 </div>
{% endif %}

{% endblock %}